### ISSUE TITLE
Prefix is hard-coded in form.

### ISSUE THREAD

**Issue by satary** [rcthomas/jupyterhub-announcement#25]
https://github.com/rcthomas/jupyterhub-announcement/blob/5b9488ab17d5442a0749c9ce621ad56d527c2170/templates/index.html#L17

Request in a form always lead to '/services/announcement/update'  ignoring  `c.AnnouncementService.service_prefix`.
In some deployments, the hub is not running in the root.

**Comment by rcthomas** [comment]
@satary thanks for noticing this, do you happen to have a branch that fixes this you want to craft into a PR?

**Comment by rcthomas** [comment]
Fixed in #29, released in 0.9.2
