### ISSUE TITLE
403 Forbidden when posting an update 

### ISSUE THREAD

**Issue by lifetooeasy** [rcthomas/jupyterhub-announcement#27]
After upgrade to jupyterhub **4.1.0** after writing the text in the box and click on submit I got 403 Forbidden.

I followed this [Link](https://github.com/rcthomas/jupyterhub-announcement/tree/main/examples/hub-managed) to set up the service.

With Jupyterhub **4.0.2** it works.

**Comment by rcthomas** [comment]
Can you upgrade to 4.1.5?

**Comment by lifetooeasy** [comment]
I did but it didn't help. Actually I started with 4.1.5 and dowgraded to 4.1.4 ... 4.0.2.

**Comment by rcthomas** [comment]
I've replicated the issue.  It looks like JupyterHub 4.1 introduced a change that breaks things on the service side.  I'm going to need @minrk to advise on whether we can do anything about it.

**Comment by rcthomas** [comment]
@lifetooeasy can you try with the `add-xsrf` branch?  I'll work on making a release in a few days, thanks.

**Comment by lifetooeasy** [comment]
@rcthomas it works with `add-xsrf`. Thank you for working on it.

**Comment by rcthomas** [comment]
Released in 0.9.2
